version: '3.9'
services:
  db:
    image: mongo:4.4.6
    volumes:
      - ./.db:/data/db

  api:
    build: .
    ports:
      - '8080:8080'
    environment:
      DB_CONNECT_URL: mongodb://db:27017
      JWT_KEY: F2YkkO9OezA5yO92Fn3xNBDNdlkgXgcvSGY4OxGQEvjlxEm765H71vJFk5LgYXH9
    depends_on:
      - db

  react:
    build:
      context: .
      dockerfile: Dockerfile.react
    volumes:
      - './:/app'
      - '/app/node_modules'
    depends_on:
      - api

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx:/etc/nginx/templates
    ports:
      - '80:80'
    environment:
      - NGINX_PORT=80
    depends_on:
      - react
